services:
  init-rentals:
    image: ${OKTETO_BUILD_RENTALS_IMAGE}
    command: yarn load
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=mongodb123root
      - MONGODB_DATABASE=okteto
      - MONGODB_HOST=mongodb-rentals
    restart: never
    depends_on:
      mongodb-rentals:
        condition: service_healthy

  mongodb-rentals:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb123root
      - MONGO_INITDB_DATABASE=okteto
    ports:
      - 27017
    volumes:
      - data-rentals:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  data-rentals:
