apiVersion: v1
kind: Service
metadata:
  name: mongodb-rentals-svc
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    app.kubernetes.io/name: mongodb-rentals
    app.kubernetes.io/instance: {{ .Release.Name }}