apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  username: b2t0ZXRv # okteto
  password: bW9uZ29kYjEyMw== # mongodb123